config/routes.rb
TempBlog::Application.routes.draw do
  
  resources :series

  resources :tags
  resources :primary_categories
  resources :tutorial_types
  resources :tutorial_states
  resources :tutorial_times
  resources :tutorial_modes
  resources :users

  get "home/index"
  get "home/default"
  get "home/blog"

  resources :tutorials
  match '/TutorialsList', :to => 'tutorials#tutorials_list', :via => [:get]
  match '/ShowTutorial/:id', :to => 'tutorials#show_tutorial', :via => [:get]
  match '/ShowTutorialDetails/:id', :to => 'tutorials#show_tutorial_details', :via => [:get]

  match '/:slug' => 'home#show_tutorial_using_slug'

  

  get "demo/page1"
  get "demo/page2"
  get "demo/page3"

  root :to => 'home#index'

end

app/models/tutorial_time.rb
class TutorialTime < ActiveRecord::Base
  attr_accessible :name, :status
end

app/controllers/tutorial_times_controller.rb
class TutorialTimesController < ApplicationController

  layout 'admin_application'
  def index
    @tutorial_times = TutorialTime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutorial_times }
    end
  end

  def show
    @tutorial_time = TutorialTime.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @tutorial_time }
    end
  end

  def new
    @tutorial_time = TutorialTime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tutorial_time }
    end
  end

  def edit
    @tutorial_time = TutorialTime.find(params[:id])
  end

  def create
    @tutorial_time = TutorialTime.new(params[:tutorial_time])

    respond_to do |format|
      if @tutorial_time.save
        format.html { redirect_to @tutorial_time, notice: 'Tutorial time was successfully created.' }
        format.json { render json: @tutorial_time, status: :created, location: @tutorial_time }
      else
        format.html { render action: "new" }
        format.json { render json: @tutorial_time.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tutorial_time = TutorialTime.find(params[:id])

    respond_to do |format|
      if @tutorial_time.update_attributes(params[:tutorial_time])
        format.html { redirect_to @tutorial_time, notice: 'Tutorial time was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutorial_time.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tutorial_time = TutorialTime.find(params[:id])
    @tutorial_time.destroy

    respond_to do |format|
      format.html { redirect_to tutorial_times_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tutorial_times_helper.rb
module TutorialTimesHelper
end

app/views/tutorial_times/_form.html.erb
<%= form_for(@tutorial_time) do |f| %>
  <% if @tutorial_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial_time.errors.count, "error") %> prohibited this tutorial_time from being saved:</h2>

      <ul>
      <% @tutorial_time.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutorial_times/edit.html.erb
<h1>Editing Tutorial Time</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutorial_time %> |
<%= link_to 'Back', tutorial_times_path %>

app/views/tutorial_times/index.html.erb
<h1>Tutorial Times</h1>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Options</th>
  </tr>

<% @tutorial_times.each do |tutorial_time| %>
  <tr>
    <td><%= tutorial_time.name %></td>
    <td><%= tutorial_time.status %></td>
    <td><%= link_to 'Show', tutorial_time %> | <%= link_to 'Edit', edit_tutorial_time_path(tutorial_time) %> | <%= link_to 'Destroy', tutorial_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tutorial time', new_tutorial_time_path %>

app/views/tutorial_times/new.html.erb
<h1>New Tutorial Times</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorial_times_path %>

app/views/tutorial_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tutorial_time.name %>
</p>

<p>
  <b>Status:</b>
  <%= @tutorial_time.status %>
</p>


<%= link_to 'Edit', edit_tutorial_time_path(@tutorial_time) %> |
<%= link_to 'Back', tutorial_times_path %>