config/routes.rb
TempBlog::Application.routes.draw do
  
  resources :series

  resources :tags
  resources :primary_categories
  resources :tutorial_types
  resources :tutorial_states
  resources :tutorial_times
  resources :tutorial_modes
  resources :users

  get "home/index"
  get "home/default"
  get "home/blog"

  resources :tutorials
  match '/TutorialsList', :to => 'tutorials#tutorials_list', :via => [:get]
  match '/ShowTutorial/:id', :to => 'tutorials#show_tutorial', :via => [:get]
  match '/ShowTutorialDetails/:id', :to => 'tutorials#show_tutorial_details', :via => [:get]

  match '/:slug' => 'home#show_tutorial_using_slug'

  

  get "demo/page1"
  get "demo/page2"
  get "demo/page3"

  root :to => 'home#index'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  layout 'admin_application'

  def index
    @series = Series.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @series }
    end
  end

  def show
    @series = Series.find(params[:id])
    @tutorial_specific_to_series = Tutorial.where(:series_id => @series.id ).order("tutorial_order ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series }
    end
  end

  def new
    @series = Series.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series }
    end
  end

  def edit
    @series = Series.find(params[:id])
  end

  def create
    @series = Series.new(params[:series])
    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render json: @series, status: :created, location: @series }
      else
        format.html { render action: "new" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @series = Series.find(params[:id])

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end
end

app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-8">
    <b>Series Name</b><br/>
    <%= f.text_field :name, :class => "col-md-12"  %>
  </div>
  <div class="col-md-4">
    <b>Status</b><br />
    <%= f.check_box :status %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <b>Short Description</b><br/>
    <%= f.text_area :short_description, :cols => 40, :rows => 5, :class => "col-md-12"  %>
  </div>
</div>  

<div class="row">
  <div class="col-md-12">
    <b>Tag</b><br/>
    <%= f.text_field :tag, :class => "col-md-12"  %>
  </div>
</div>  

<div class="row">
  <div class="col-md-4">
    <b>Vote Up</b><br/>
    <%= f.number_field :vote_up %>
  </div>
  <div class="col-md-4">
    <b>Total View</b><br/>
    <%= f.number_field :total_view %>
  </div>
  <div class="col-md-4">
    <% f.submit %><br/>
    <% if controller.action_name == "edit"%>
      <input type="submit" value="Update" name="commit" class="btn btn-primary btn-sm">
    <% else %>
      <input type="submit" value="Create" name="commit" class="btn btn-primary btn-sm">
    <% end %>
  </div>
</div>

<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Series</h1>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <!--
    <th>Short description</th>
    <th>Tag</th>
    -->
    <th>Status</th>
    
    <!--<th>Series picture file name</th>
    <th>Series picture content type</th>
    <th>Series picture file size</th>
    <th>Series picture updated at</th>
    -->
    <th>Vote up</th>
    <th>Total view</th>
    <th>Slug</th>
    <th>Options</th>
  </tr>

<% @series.each do |series| %>
  <tr>
    <td><%= series.name %></td>
    <!--
    <td><%= series.short_description %></td>
    <td><%= series.tag %></td> -->
    
    <td><%= series.status %></td>
    <!--<td><%= series.series_picture_file_name %></td>
    <td><%= series.series_picture_content_type %></td>
    <td><%= series.series_picture_file_size %></td>
    <td><%= series.series_picture_updated_at %></td> -->
    <td><%= series.vote_up %></td>
    <td><%= series.total_view %></td>
    <td><%= series.slug %></td>
    <td><%= link_to 'Show', series %> | <%= link_to 'Edit', edit_series_path(series) %> | <%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-8">
    <b>Series Name</b><br/>
    <%= @series.name %>
  </div>
  <div class="col-md-4">
    <b>Status</b><br />
    <%= @series.status %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <b>Short Description</b><br/>
    <%= @series.short_description %>
  </div>
</div> 

<div class="row">
  <div class="col-md-12">
    <b>Tag</b><br/>
    <%= @series.tag %>
  </div>
</div>  
<!--
<div class="row">
  <div class="col-md-12">
    <b>slug</b><br/>
    <%= @series.slug %>
  </div>
</div>  
-->
<div class="row">
  <div class="col-md-4">
    <b>Vote Up</b><br/>
    <%= @series.vote_up %>
  </div>
  <div class="col-md-4">
    <b>Total View</b><br />
    <%= @series.total_view %>
  </div>
  <div class="col-md-4">
    <br/>
    <%= link_to 'Edit', edit_series_path(@series) %> | <%= link_to 'Back', series_index_path %>
  </div>
</div>
<hr/>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <b><%= @series.name %></b>    
  </div>

  <!-- List group -->
  <% #@tutorial = Tutorial.where("series_id = ?", @series.id ).order("series.order") %>
  <ul class="list-group">
    <% if !@tutorial_specific_to_series.present? %>
      <li class="list-group-item"> No Such Tutorial is present</li>
    <% end %>

    <% @tutorial_specific_to_series.each do |tutorial_list| %>
      <li class="list-group-item"><%=tutorial_list.tutorial_order %> :: <%=tutorial_list.title%></li>
    <% end %>

  </ul>
</div>